application: emomentumintranet-1009
version: 5
runtime: php55
api_version: 1

handlers:

- url: /assets/js/*
  static_dir: assets/js
  
- url: /assets/css/*
  static_dir: assets/css
  
- url: /assets/fonts/*
  static_dir: assets/fonts
  
- url: /AdminAssets/js/*
  static_dir: AdminAssets/js
  
- url: /AdminAssets/fonts/*
  static_dir: AdminAssets/fonts

- url: /AdminAssets/css/*
  static_dir: AdminAssets/css

- url: /assets/images/*
  static_dir: assets/images

- url: /
  script: index.php

- url: /(.+)
  script: index.php